<!DOCTYPE html>
<html>
    <head>
        <center>
        <title>MUY JAVASCRIPT</title>
    </head>
    <body>
        <h1 style="color:red;">PHP NEW SERVER KUSHAL BERA</h1>
        <?php
        $AAS=46;
        $JS=48;
        
        //SIMPLE ASSIGMENT OPRATOR
        $AA=$AAS+$JS;
        echo 'MY SIMPLE ASSIGMENT OPRATOR:'.$AA.'<BR>'.'<BR>';

         $AA +=$AAS;
        echo 'MY ADDITION AND ASSIGMENT OPRATOR:'.$AA.'<BR>'.'<BR>';
        
         $AA -=$AAS;
        echo 'MY SUBTRATION AND ASSIGMENT OPRATOR:'.$AA.'<BR>'.'<BR>';
        
         $AA *=$AAS;
        echo 'MY MULTIPLY AND ASSIGMENT OPRATOR:'.$AA.'<BR>'.'<BR>';

         $AA /=$AAS;
        echo 'MY DIVISION AND ASSIGMENT OPRATOR:'.$AA.'<BR>'.'<BR>';

         $AA %=$AAS;
        echo 'MY MODULUS AND ASSIGMENT OPRATOR:'.$AA.'<BR>'.'<BR>';
        
        
        