<!DOCTYPE html>
<html>
    <head>
        <center>
        <title>MUY JAVASCRIPT</title>
    </head>
    <body>
        <h1>PHP NEW SERVER KUSHAL BERA</h1>
        <?php
$as=22;
$ad='KUSHAL BERA';
$aa=14;
echo$aa++.'<br>';
echo'MY INCREMENT RESULT:'.$aa.'<br>';
echo'MY NAME IS:'.$ad.'<BR>';
echo'MY ADDITION RESULT:'.$as+12;
$a=12;
$b=1;
if($a>=10||$b>=10){
echo 'BOTH VARIALE GRETERDHAN';
}else{
    echo 'AT LEAST ONE VARIBLE IS GREATER THAN 10.\n';

}
        ?>